[package]
name = "twitch-tui"
version = "1.6.0"
authors = ["Xithrius <xithrius@gmail.com>"]
edition = "2018"
description = "Twitch chat in the terminal."
documentation = "https://github.com/Xithrius/twitch-tui"
homepage = "https://github.com/Xithrius/twitch-tui"
repository = "https://github.com/Xithrius/twitch-tui"
license = "MIT OR Apache-2.0"
keywords = ["tui", "twitch"]
categories = ["command-line-utilities"]

[dependencies]
crossterm = "0.20.0"
tui = { version = "0.16.0", default-features = false, features = ["crossterm"] }
anyhow = "1.0.52"
unicode-width = "0.1.9"
unicode-segmentation = "1.8.0"
chrono = "0.4"
irc = "0.15.0"
futures = "0.3.19"
tokio = { version = "1.15.0", features = ["full"] }
toml = "0.5.8"
serde = { version = "1.0.132", features = ["derive"] }
textwrap = "0.14.2"
rustyline = "9.1.1"
lazy_static = "1.4.0"
clap = { version = "2.34.0", features = ["yaml"] }
enum-iterator = "0.7.0"
fuzzy-matcher = "0.3.7"
regex = "1.5.4"

[[bin]]
bench = false
path = "src/main.rs"
name = "twt"
