[package]
name = "twitch-tui"
version = "2.0.0-alpha.12"
authors = ["Xithrius <xithrius@gmail.com>"]
edition = "2021"
rust-version = "1.61.0"
description = "Twitch chat in the terminal."
documentation = "https://github.com/Xithrius/twitch-tui"
homepage = "https://github.com/Xithrius/twitch-tui"
repository = "https://github.com/Xithrius/twitch-tui"
license = "MIT OR Apache-2.0"
keywords = ["tui", "twitch"]
categories = ["command-line-utilities"]

[dependencies]
crossterm = "0.25.0"
tui = { version = "0.19.0", default-features = false, features = [ "crossterm" ] }
tokio = { version = "1.21.1", features = [ "full" ] }
clap = { version = "4.0.7", features = [ "derive", "cargo" ] }
serde = { version = "1.0.144", features = [ "derive" ] }
serde_json = "1.0.85"
unicode-width = "0.1.10"
unicode-segmentation = "1.10.0"
chrono = "0.4.22"
irc = "0.15.0"
futures = "0.3.24"
toml = "0.5.9"
textwrap = "0.15.1"
rustyline = "10.0.0"
lazy_static = "1.4.0"
fuzzy-matcher = "0.3.7"
regex = "1.6.0"
color-eyre = "0.6.2"
log = "0.4.17"
fern = "0.6.1"

[[bin]]
bench = false
path = "src/main.rs"
name = "twt"

[profile.dev]
lto = "off"

[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
lto = "thin"
debug = 1
incremental = true
