[package]
name = "twitch-tui"
version = "2.0.0-alpha.3"
authors = ["Xithrius <xithrius@gmail.com>"]
edition = "2021"
rust-version = "1.58.1"
description = "Twitch chat in the terminal."
documentation = "https://github.com/Xithrius/twitch-tui"
homepage = "https://github.com/Xithrius/twitch-tui"
repository = "https://github.com/Xithrius/twitch-tui"
license = "MIT OR Apache-2.0"
keywords = ["tui", "twitch"]
categories = ["command-line-utilities"]

[dependencies]
crossterm = "0.23.2"
tui = { version = "0.18.0", default-features = false, features = [ "crossterm" ] }
tokio = { version = "1.18.2", features = [ "full" ] }
serde = { version = "1.0.137", features = [ "derive" ] }
clap = { version = "3.1.1", features = [ "derive" ] }
anyhow = "1.0.57"
unicode-width = "0.1.9"
unicode-segmentation = "1.9.0"
chrono = "0.4"
irc = "0.15.0"
futures = "0.3.21"
toml = "0.5.9"
textwrap = "0.15.0"
rustyline = "9.1.2"
lazy_static = "1.4.0"
enum-iterator = "0.8.1"
fuzzy-matcher = "0.3.7"
rusqlite = "0.27.0"
regex = "1.5.5"
ureq = "2.4.0"

[target.'cfg(windows)'.dependencies]
rusqlite = { version = "0.27.0", features = [ "winsqlite3"] }

[[bin]]
bench = false
path = "src/main.rs"
name = "twt"
