[package]
name = "terminal-twitch-chat"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.42"
tui = "0.15"
termion = "1.5"
rand = "0.8.4"
unicode-width = "0.1.5"
chrono = "0.4"
irc = "0.15.0"
futures = "0.3.17"
tokio = { version = "1.11.0", features = ["full"] }
dotenv = "0.15.0"
toml = "0.5.8"
serde = "1.0.130"
textwrap = "0.14.2"
