[package]
name = "twitch-tui"
version = "2.6.3"
authors = ["Xithrius <xithrius@gmail.com>"]
edition = "2021"
rust-version = "1.75.0"
description = "Twitch chat in the terminal."
documentation = "https://github.com/Xithrius/twitch-tui"
homepage = "https://github.com/Xithrius/twitch-tui"
repository = "https://github.com/Xithrius/twitch-tui"
license = "MIT OR Apache-2.0"
keywords = ["tui", "twitch"]
categories = ["command-line-utilities"]

[dependencies]
crossterm = "0.27.0"
tui = { package = "ratatui", version = "0.26.0", default-features = false, features = [ "crossterm", "serde", "underline-color" ] }
tokio = { version = "1.36.0", features = [ "rt", "macros", "rt-multi-thread", "fs" ] }
clap = { version = "4.5.0", features = [ "derive", "cargo" ] }
serde = { version = "1.0.196", features = [ "derive" ] }
serde_json = "1.0.113"
unicode-width = "0.1.11"
unicode-segmentation = "1.11.0"
chrono = "0.4.33"
irc = "0.15.0"
futures = "0.3.30"
toml = "0.8.9"
textwrap = "0.16.0"
rustyline = "10.1.1"
fuzzy-matcher = "0.3.7"
regex = "1.10.3"
color-eyre = "0.6.2"
log = "0.4.20"
fern = "0.6.2"
dialoguer = { version = "0.11.0", default-features = false }
reqwest = { version = "0.11.24", features = [ "json" ] }
image = "0.24.8"
base64 = "0.21.7"
tempfile = "3.10.0"
serde_with = "3.6.0"
once_cell = "1.19.0"
webbrowser = "0.8.12"
memchr = "2.7.1"
webp-animation = { version = "0.9.0", features = ["image"] }

[features]
static-webp = ["webp-animation/static"]

[[bin]]
bench = false
path = "src/main.rs"
name = "twt"

[profile.dev]
lto = "off"

[profile.release]
lto = "thin"
debug = 1
