[package]
name = "terminal-twitch-chat"
version = "1.1.3"
authors = ["Xithrius <xithrius@gmail.com>"]
edition = "2018"
description = "Twitch chat in the terminal."
documentation = "https://github.com/Xithrius/terminal-twitch-chat"
homepage = "https://github.com/Xithrius/terminal-twitch-chat"
repository = "https://github.com/Xithrius/terminal-twitch-chat"
license = "MIT OR Apache-2.0"
keywords = ["tui", "twitch"]
categories = ["command-line-utilities"]

[dependencies]
crossterm = "0.21.0"
tui = { version = "0.16.0", default-features = false, features = ["crossterm"] }
anyhow = "1.0.44"
rand = "0.8.4"
unicode-width = "0.1.9"
unicode-segmentation = "1.8.0"
chrono = "0.4"
irc = "0.15.0"
futures = "0.3.17"
tokio = { version = "1.12.0", features = ["full"] }
toml = "0.5.8"
serde = { version = "1.0.130", features = ["derive"] }
textwrap = "0.14.2"
dirs = "4.0.0"
rustyline = "9.0.0"
lazy_static = "1.4.0"

[[bin]]
bench = false
path = "src/main.rs"
name = "ttc"
