[package]
name = "twitch-tui"
version = "2.0.2"
authors = ["Xithrius <xithrius@gmail.com>"]
edition = "2021"
rust-version = "1.61.0"
description = "Twitch chat in the terminal."
documentation = "https://github.com/Xithrius/twitch-tui"
homepage = "https://github.com/Xithrius/twitch-tui"
repository = "https://github.com/Xithrius/twitch-tui"
license = "MIT OR Apache-2.0"
keywords = ["tui", "twitch"]
categories = ["command-line-utilities"]

[dependencies]
crossterm = "0.26.1"
tui = { version = "0.19.0", default-features = false, features = [ "crossterm" ] }
tokio = { version = "1.24.1", features = [ "rt", "macros", "rt-multi-thread" ] }
clap = { version = "4.1.6", features = [ "derive", "cargo" ] }
serde = { version = "1.0.152", features = [ "derive" ] }
serde_json = "1.0.91"
unicode-width = "0.1.10"
unicode-segmentation = "1.10.0"
chrono = "0.4.23"
irc = "0.15.0"
futures = "0.3.25"
toml = "0.7.1"
textwrap = "0.16.0"
rustyline = "10.1.0"
lazy_static = "1.4.0"
fuzzy-matcher = "0.3.7"
regex = "1.7.0"
color-eyre = "0.6.2"
log = "0.4.17"
fern = "0.6.1"
dialoguer = { version = "0.10.3", default-features = false }

[[bin]]
bench = false
path = "src/main.rs"
name = "twt"

[profile.dev]
lto = "off"

[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
lto = "thin"
debug = 1
