[twitch]
# Your username on Twitch.
username = ""
# The streamer's name.
channel = ""
# The IRC channel you'd like to connect to.
server = "irc.chat.twitch.tv"
# OAuth token that authenticates you into Twitch. Acquired through https://twitchapps.com/tmi/.
token = ""

[terminal]
# The delay in milliseconds between terminal updates.
tick_delay = 30
# The maximum amount of messages to be stored.
maximum_messages = 150
# The file path to log to.
log_file = ""
# The state the application will start in.
start_state = "normal"

[storage]
# If previous channels switched to should be tracked.
channels = true
# If previous username mentions should be tracked.
mentions = true

[filters]
# If filters should be enabled at all.
enabled = false
# If the regex filters should be reversed.
reversed = false

[frontend]
# If the time and date is to be shown.
date_shown = true
# The format of the date and time outputs. Formats can be found at https://strftime.org/.
date_format = "%a %b %e %T %Y"
# The longest a username can be.
maximum_username_length = 26
# Which side the username should be aligned to.
username_alignment = "right"
# The color palette for the username column: pastel (default), vibrant, warm, cool.
palette = "pastel"
# Show title with time and channel.
title_shown = true
# The amount of space between the chat window and the terminal border.
margin = 0
# Show twitch badges next to usernames.
badges = true
# The theme of the frontend, dark (default), or light.
theme = "dark"
# If the user's name appears in chat, highlight it.
username_highlight = true
# The shape of the cursor, block (default), underscore, or line.
cursor_shape = "block"
# If the scrolling should be inverted.
inverted_scrolling = false
