[package]
name = "twitch-tui"
version = "2.3.0"
authors = ["Xithrius <xithrius@gmail.com>"]
edition = "2021"
rust-version = "1.61.0"
description = "Twitch chat in the terminal."
documentation = "https://github.com/Xithrius/twitch-tui"
homepage = "https://github.com/Xithrius/twitch-tui"
repository = "https://github.com/Xithrius/twitch-tui"
license = "MIT OR Apache-2.0"
keywords = ["tui", "twitch"]
categories = ["command-line-utilities"]

[dependencies]
crossterm = "0.26.1"
tui = { package = "ratatui", version = "0.20.1", default-features = false, features = [ "crossterm", "serde" ] }
tokio = { version = "1.28.1", features = [ "rt", "macros", "rt-multi-thread", "fs" ] }
clap = { version = "4.3.0", features = [ "derive", "cargo" ] }
serde = { version = "1.0.163", features = [ "derive" ] }
serde_json = "1.0.96"
unicode-width = "0.1.10"
unicode-segmentation = "1.10.1"
chrono = "0.4.24"
irc = "0.15.0"
futures = "0.3.28"
toml = "0.7.4"
textwrap = "0.16.0"
rustyline = "10.1.1"
lazy_static = "1.4.0"
fuzzy-matcher = "0.3.7"
regex = "1.8.2"
color-eyre = "0.6.2"
log = "0.4.17"
fern = "0.6.2"
dialoguer = { version = "0.10.4", default-features = false }
reqwest = { version = "0.11.18", features = ["json"]}
image = "0.24.6"
base64 = "0.21.1"
tempfile = "3.5.0"
anyhow = "1.0.71"
serde_with = "3.0.0"

[[bin]]
bench = false
path = "src/main.rs"
name = "twt"

[profile.dev]
lto = "off"

[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
lto = "thin"
debug = 1
